CREATE TABLE BankUser (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    UserId VARCHAR NOT NULL UNIQUE,
    CreatedAt TIMESTAMP NOT NULL,
    ModifiedAt TIMESTAMP
);

CREATE TABLE Loan (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    UserId VARCHAR NOT NULL UNIQUE,
    CreatedAt TIMESTAMP NOT NULL,
    ModifiedAt TIMESTAMP,
    Amount DECIMAL NOT NULL,
    FOREIGN KEY (UserId) REFERENCES BankUser (UserId)
);

CREATE TABLE Deposit (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    BankUserId INTEGER NOT NULL,
    CreatedAt TIMESTAMP NOT NULL,
    Amount DECIMAL NOT NULL,
    FOREIGN KEY (BankUserId) REFERENCES BankUser (id)
);

CREATE TABLE Accont(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    BankUserId INTEGER NOT NULL UNIQUE,
    AccountNo INTEGER NOT NULL,
    IsStudent BOOLEAN NOT NULL,
    CreatedAt TIMESTAMP NOT NULL,
    ModifiedAt TIMESTAMP NOT NULL,
    InterestRate NUMBER NOT NULL,
    Amount DECIMAL NOT NULL,
    FOREIGN KEY (BankUserId) REFERENCES BankUser (id)
);