DROP TABLE IF EXISTS SkatUser;
DROP TABLE IF EXISTS SkatYear;
DROP TABLE IF EXISTS SkatUserYear;

CREATE TABLE SkatUser(
Id INTEGER PRIMARY KEY AUTOINCREMENT,
UserId VARCHAR UNIQUE NOT NULL,
CreatedAt TIMESTAMP NOT NULL,
IsActive BIT NOT NULL
);

CREATE TABLE SkatYear(
Id INTEGER PRIMARY KEY AUTOINCREMENT,
Label VARCHAR UNIQUE NOT NULL,
CreatedAt TIMESTAMP NOT NULL,
ModifiedAt TIMESTAMP,
StartDate DATE NOT NULL,
EndDate DATE NOT NULL
);

CREATE TABLE SkatUserYear(
Id INTEGER PRIMARY KEY AUTOINCREMENT,
SkatUserId INTEGER,
SkatYearId INTEGER,
UserId VARCAHR NOT NULL,
IsPaid BIT NOT NULL,
Amount INTEGER NOT NULL,
FOREIGN KEY (SkatUserId) REFERENCES SkatUser(Id) ON DELETE CASCADE,
FOREIGN KEY (SkatYearId) REFERENCES SkatYear(Id) ON DELETE CASCADE
);

